version: "3"

services:
  tutorial-prisma:
    image: node:16
    ports:
      - 5555:5555

  tutorial-prisma-db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tutorialprisma
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    hostname: tutorial-prisma-db
